#!/usr/bin/env python3
"""
Generate enum classes from OpenAPI schema with x-ms-enum extension.
This complements Kiota code generation by creating actual enum types.
"""

import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

SWAGGER_URL = "http://localhost:5053/swagger/v1/swagger.json"
OUTPUT_DIR = Path("Services/Generated/Models")

ENUM_TEMPLATE = """// <auto-generated/>
#pragma warning disable CS0618
namespace MedizID.UI.Services.Generated.Models
{{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum {enum_name}
    #pragma warning restore CS1591
    {{
{values}
    }}
}}
#pragma warning restore CS0618
"""


def generate_enums():
    """Generate enum files from OpenAPI schema."""
    try:
        print("🔄 Generating enum classes from OpenAPI schema...")

        # Fetch OpenAPI schema
        try:
            with urllib.request.urlopen(SWAGGER_URL, timeout=5) as response:
                schema = json.loads(response.read().decode("utf-8"))
        except urllib.error.URLError as e:
            raise Exception(f"Failed to fetch OpenAPI schema: {e}")

        # Create output directory
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

        # Get all schemas
        schemas = schema.get("components", {}).get("schemas", {})

        # Find and generate enum classes
        enum_count = 0
        for schema_name, schema_def in schemas.items():
            if "x-ms-enum" in schema_def:
                enum_data = schema_def["x-ms-enum"]
                enum_name = enum_data.get("name", schema_name)
                values_list = enum_data.get("values", [])

                # Generate values string
                values = "\n".join(
                    f"        {v['name']} = {v['value']}," for v in values_list
                )
                # Remove trailing comma from last value
                if values:
                    values = values.rstrip(",")

                # Generate file
                enum_code = ENUM_TEMPLATE.format(enum_name=enum_name, values=values)

                output_file = OUTPUT_DIR / f"{enum_name}.cs"
                output_file.write_text(enum_code)
                print(f"✅ Generated {output_file}")
                enum_count += 1

        if enum_count > 0:
            print(f"\n✨ Successfully generated {enum_count} enum classes!")
            return 0
        else:
            print("⚠️  No enums found with x-ms-enum extension")
            return 1

    except Exception as e:
        print(f"❌ Error generating enums: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(generate_enums())
