#!/bin/bash

# Generate enums from OpenAPI schema
# This script creates enum files that Kiota can't generate automatically

set -e

SWAGGER_URL="http://localhost:5053/swagger/v1/swagger.json"
OUTPUT_DIR="Services/Generated/Models"

echo "🔄 Generating enum classes from OpenAPI schema..."

# Create enums directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# UserRoleEnum
curl -s "$SWAGGER_URL" | jq -r '.components.schemas.UserRoleEnum | "// <auto-generated/>\n#pragma warning disable CS0618\nnamespace MedizID.Web.Services.Generated.Models\n{\n    [global::System.CodeDom.Compiler.GeneratedCode(\"Kiota\", \"1.0.0\")]\n    #pragma warning disable CS1591\n    public enum UserRoleEnum\n    #pragma warning restore CS1591\n    {\n\(.\"x-ms-enum\".values[] | \"        \(.name) = \(.value),\") | rtrimstr(\",\") | \n    \}\n}\n#pragma warning restore CS0618"' > "$OUTPUT_DIR/UserRoleEnum.cs" 2>/dev/null || echo "Failed to generate UserRoleEnum"

# FacilityTypeEnum
curl -s "$SWAGGER_URL" | jq -r '.components.schemas.FacilityTypeEnum | "// <auto-generated/>\n#pragma warning disable CS0618\nnamespace MedizID.Web.Services.Generated.Models\n{\n    [global::System.CodeDom.Compiler.GeneratedCode(\"Kiota\", \"1.0.0\")]\n    #pragma warning disable CS1591\n    public enum FacilityTypeEnum\n    #pragma warning restore CS1591\n    {\n\(.\"x-ms-enum\".values[] | \"        \(.name) = \(.value),\") | rtrimstr(\",\") | \n    \}\n}\n#pragma warning restore CS0618"' > "$OUTPUT_DIR/FacilityTypeEnum.cs" 2>/dev/null || echo "Failed to generate FacilityTypeEnum"

# InstallationType
curl -s "$SWAGGER_URL" | jq -r '.components.schemas.InstallationType | "// <auto-generated/>\n#pragma warning disable CS0618\nnamespace MedizID.Web.Services.Generated.Models\n{\n    [global::System.CodeDom.Compiler.GeneratedCode(\"Kiota\", \"1.0.0\")]\n    #pragma warning disable CS1591\n    public enum InstallationType\n    #pragma warning restore CS1591\n    {\n\(.\"x-ms-enum\".values[] | \"        \(.name) = \(.value),\") | rtrimstr(\",\") | \n    \}\n}\n#pragma warning restore CS0618"' > "$OUTPUT_DIR/InstallationType.cs" 2>/dev/null || echo "Failed to generate InstallationType"

echo "✅ Enum classes generated successfully!"

